### ISSUE TITLE
linux support?

### ISSUE THREAD

**Issue by 3ibod** [Mr-Craig/AsyncTickPhysics#13]
![image](https://github.com/Mr-Craig/AsyncTickPhysics/assets/58691873/e45596ec-14df-422d-849c-72d1285f0c12)
Hello. Can this plugin work on Linux? When opening a font from a plugin created in Windows, I get an error that there is no existing class, and in the list of blueprints I only find AsyncPhysicsData 
Tested on versions 5.3 and 5.3.2

**Comment by Mr-Craig** [comment]
It doesn't look like the plugin is enabled, click the checkbox next to the plugin and restart the editor.

**Comment by 3ibod** [comment]
It's turned on, I accidentally clicked the turn off checkbox. The problem still remains
![image](https://github.com/Mr-Craig/AsyncTickPhysics/assets/58691873/c1971785-1fb3-4679-88e4-13427da890e7)

**Comment by 3ibod** [comment]
![image](https://github.com/Mr-Craig/AsyncTickPhysics/assets/58691873/8966570f-2bfb-4100-b734-6c0d3c14a061)

**Comment by 3ibod** [comment]
Ok, I recompiled the plugin in several ways but to no avail. It turned out that in the plugin file you need to delete the line "EngineVersion": "5.3.0".

Otherwise, if the line with the plugin version matches the engine version, then it will not start, and if you add the patch number (5.3.2), the engine will start but the plugin will not turn on

Anyway, thanks for the great plugin.
