### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by MooncakeEstLa** [Mr-Craig/AsyncTickPhysics#15]
Hey just a quick question,

Does this plugins replaces the built-in event "**Async Physics Ticks**" that is present at in UE5 (I'm using 5.4)?
![image](https://github.com/Mr-Craig/AsyncTickPhysics/assets/13868345/43f4e1c3-33c5-4e0f-a98c-993276a73072)
And do we need to change the **Physics Settings** and tick the checkbox "**Tick Physics Async**" like so to make it work with your plugin ?
![image](https://github.com/Mr-Craig/AsyncTickPhysics/assets/13868345/b69eb8a0-b68a-4a54-93f7-454a6a8dd07d)

Also I'm a bit lost on how this works really, that would be super nice to have a simple example on how to use controls and the plugin, like a very simple controllable ball would be nice to better understand.

Cheers!

**Comment by Mr-Craig** [comment]
> Does this plugins replaces the built-in event "**Async Physics Ticks**" that is present at in UE5 (I'm using 5.4)? 

No it doesn't, Epic added the Async Physics Tick event in unreal 5.1 so it's still in the plugin for anyone using 5.0

> And do we need to change the Physics Settings and tick the checkbox "Tick Physics Async" like so to make it work with your plugin ?

Yes you need to check that box and adjust the delta time to suit your project

> Also I'm a bit lost on how this works really, that would be super nice to have a simple example on how to use controls and the plugin, like a very simple controllable ball would be nice to better understand.

All this plugin does is allow you to access the async tick in blueprints and then you can use the provided ATP_* functions to manipulate an object on the physics thread.

To create a controllable ball you would need to calculate the direction and then apply a force to the object on the physics thread using a function such as ATP_AddForce or ATP_AddImpulse, remembering to only use those functions inside the Async Physics Tick event.
