### ISSUE TITLE
ue5 crash

### ISSUE THREAD

**Issue by benjdarling** [Mr-Craig/AsyncTickPhysics#2]
Repro: 
Async Pawn has scene components using scene component blueprints
Calling an update on the scene components to sphere trace into the scene via asyncpawn async tick update

Crash log:

Assertion failed: !bPostTickComponentUpdate [File:D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\LevelTick.cpp] [Line: 907]

UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_Engine
UnrealEditor_AsyncTickPhysics!AAsyncTickPawn::AsyncTick() [C:\Users\alexc\Desktop\AsyncTickPhysics\AsyncTickPhysics\HostProject\Plugins\AsyncTickPhysics\Intermediate\Build\Win64\UnrealEditor\Inc\AsyncTickPhysics\AsyncTickPawn.gen.cpp:23]
UnrealEditor_AsyncTickPhysics!FAsyncPhysicsCallback::OnPreSimulate_Internal() [C:\Users\alexc\Desktop\AsyncTickPhysics\AsyncTickPhysics\HostProject\Plugins\AsyncTickPhysics\Source\AsyncTickPhysics\Private\AsyncTickCallback.cpp:19]
UnrealEditor_Chaos
UnrealEditor_Chaos
UnrealEditor_Chaos
UnrealEditor_Chaos
UnrealEditor_Chaos
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_Core
kernel32
ntdll

**Comment by benjdarling** [comment]
update: appears it might be related to trying to "draw debug" on the traces

**Comment by Mr-Craig** [comment]
Yes thats the cause, you cannot use any of the DrawDebug functions outside of the game thread. You can still use traces but you cannot enable the Draw Debug option. If you really need the Debug lines I would suggest you call the Trace function inside a regular Tick or Timer Event and store the result inside a variable which can be used inside the Async Tick Event.
