### ISSUE TITLE
Get transform

### ISSUE THREAD

**Issue by SlartiBADFAT** [Mr-Craig/AsyncTickPhysics#3]
Hi! Great plugin, thanks a lot for the work!) Is it possible to add a "get transform component" node?

**Comment by Mr-Craig** [comment]
You can already get the transform of any component by using the ATP_GetTransform function

**Comment by SlartiBADFAT** [comment]
As far as I understand, the get transform presented in the plugin allows you to interact with the mesh only, in any case, I couldn't get it to work with the scene component

**Comment by Mr-Craig** [comment]
You should probably just use the regular get transform node since the physics thread wouldn't change the position of a scenecomponent

**Comment by SlartiBADFAT** [comment]
If I'm not mistaken, the usual "get transform" is tied to the event tick, which causes problems

**Comment by Mr-Craig** [comment]
> If I'm not mistaken, the usual "get transform" is tied to the event tick, which causes problems

you should be fine to call this from the async tick, you only use the ATP functions to get the correct values from the physics thread but since scene components aren't changed by it you should be fine!
