### ISSUE TITLE
Pawn Iteration should continue instead of returning in AsyncTickCallback.cpp

### ISSUE THREAD

**Issue by DragonStorm97** [Mr-Craig/AsyncTickPhysics#4]
As Title says,
in AsyncTickCallback.cpp Line 23, the `return` should be a `continue`.
Currently it will stop iterating through the rest of the pawns (and not call the tick for them) if it reaches a pawn that is not valid.
It should rather `continue` to the next one.

**Comment by Mr-Craig** [comment]
fixed it, thanks!
