### ISSUE TITLE
Linetrace support

### ISSUE THREAD

**Issue by gnwarel123** [Mr-Craig/AsyncTickPhysics#5]
When does a linetrace in physics async event ue5 crashes :/

**Comment by Mr-Craig** [comment]
Are you using the Draw Debug options?

**Comment by Mr-Craig** [comment]
> I'm using simple bp function linetracebychannel is it because it traces the debug inside bp function. I will use c++ version and replay back thank you so much for your efforts

You can use the BP LineTraceByChannel function but you cannot enable the Draw Debug functions as you can only do this on the Game Thread, setting them to None should stop the crashes!

**Comment by gnwarel123** [comment]
I will try it today thank you so much for the heads-up I'll let you know if it works. I'm making a suspension system of a car.

**Comment by gnwarel123** [comment]
Thank you so much It worked I'm happy for what you did god bless you.
